# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
tasks:
  build:
    command: "swc src --source-maps --out-dir build"
    inputs:
      - "src/**/*"
    outputs:
      - "build"
    deps:
      - "^:build"
  run:
    command:
      - 'node'
      - 'build/src/main.js'
    inputs:
      - 'src/**/*'
    deps:
      - '^:build'
