# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
tasks:
  build:
    options:
      runInCI: true
    command:
      - 'swc'
      - 'src'
      - --config='exclude=["\\.(spec|test)\\.ts$"]'
      - '--out-dir=dist'
      - '--source-maps'
      - '--strip-leading-paths'
    inputs:
      - 'src/**/*'
    outputs:
      - 'dist'
    deps:
      - '^:build'
